on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

name: Build & release

jobs:
    build:
        name: Upload Release Asset
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build for aarch64
              run: build.sh arm64
            - name: Build for armv7
              run: build.sh arm
            - name: Build for x86-64
              run: build.sh amd64

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: true
                  prerelease: false

            - name: Upload aarch64 release
              uses: actions/upload-release-asset@v1
              with:
                  asset_path: ./artifacts/ehttps-arm64.tar.gz
                  asset_name: ehttps-arm64.tar.gz

            - name: Upload armv7 release
              uses: actions/upload-release-asset@v1
              with:
                  asset_path: ./artifacts/ehttps-arm.tar.gz
                  asset_name: ehttps-arm.tar.gz

            - name: Upload x86-64 release
              uses: actions/upload-release-asset@v1
              with:
                  asset_path: ./artifacts/ehttps-amd64.tar.gz
                  asset_name: ehttps-amd64.tar.gz

